# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    rust: "1.86"
  commands:
    - apt update
    - apt install -y protobuf-compiler libssl-dev
    - pip install maturin
    - cd python && maturin develop --release

python:
  install:
    - requirements: python/docs/requirements.txt
    - method: pip
      path: python

sphinx:
  configuration: python/docs/conf.py

formats:
  - htmlzip
    